version: '3'

vars:
  HIDDEN: true
  FLAGS: []

tasks:
  dump:
    desc: "Dump internal state (hidden)"
    vars:
      FLAGS: []
    cmd: "CLI_ARGS='{{.CLI_ARGS}}' '{{.FRAMEWORK_DIR}}/lib/router/router.sh' '{{.TASK}}'"
